### ISSUE TITLE
[1.1] Implement agreed architecture @kindly

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-views#10]
This is: 
- writing a cmdline tool to:
-- Do migration to make/destroy new views
-- have a way to refresh the views
-- add in extra collections to the views
- Making the migration stuff work! 
- Specifying how the refreshing is going to work, taking into account concurrency considerations and interaction with deletion 
- Most of the work is specifying what actually goes into the views
- Making sure that the views are editable by analysts

**Comment by jpmckinney** [comment]
I'm assuming this is done.
