### ISSUE TITLE
Explore DBT (to use templating and test queries)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#101]
https://www.getdbt.com

I read about it here: https://medium.com/the-telegraph-engineering/dbt-a-new-way-to-handle-data-transformation-at-the-telegraph-868ce3964eb4

The big pros I've seen so far are:
* We can use Jinja2 in our SQL statements, which should make the SQL files easier to maintain
  * Presently, there are similar patterns that can perhaps be refactored.
* DBT offers a simple way to test the SQL files
  * Presently, we do very little testing of the SQL files themselves.
* DBT can auto-document transformation pipelines
  * Presently, dependencies between tables are undocumented. #83 #84 

In terms of cons, I haven't found anything yet (The Telegraph team mentions some in the blog post).

**Comment by kindly** [comment]
I agree this is worth a look and is very interesting.  It is very similar to an idea I had about doing such things.

My initial observations

- I really like just the select statements and that it does the table creation for you (that was what I wanted to do)
- It requires quite a lot of yml configuration to get the features to work.
-  I have written a few little frameworks before that template SQL in jinja and the output is not as easy to understand for analysts and the cases shown in the documentation are not the really difficult ones.
- The testing is not that thorough and is not something we could not do by testing the output of sql queries are what we are expecting.

My philosophy for writing the views currently was to just use pure SQL that could be run independently to make it as easy for SQL people to understand.  At the cost of some duplication.
I think a discussion about if that was the correct approach is needed.

**Comment by jpmckinney** [comment]
I didn't see so much YML configuration yet, and it seems to mostly be "configure once" (like our INI file) rather than "continuously edit". As such, it doesn't seem like a significant con – not anymore than Sphinx's relatively long conf.py file is a con.

Templating SQL in Jinja2 is optional. I agree, in principle, that plain SQL is better. That said, as files reach 400+ lines, like `007-contracts.sql`, they become hard to read and understand. The options are either to (1) break up the file into appropriate chunks; or (2) use templating to not repeat common chunks, so that readers can more easily see what's relevant.

DBT seems to help with both options, since its 'models' can be made to depend on one another, such that appropriate chunks can be broken out into separate files. We can of course break up files in the current framework, but our case the dependencies are implicit (#83), and it's possible to accidentally run one file without its dependencies.

If we were to use Jinja2, in terms of a readable version for analysts, DBT can compile the templates into plain SQL for reading. Anyway, we can postpone a decision to use Jinja2.

I think there are also opportunities with DBT to tidy up our SQL pipeline. It seems to handle things like temporary tables, but I haven't looked into it deeply.

For tests, we can of course write them like we have already (anything computable can be written again!), but instead of building up our testing framework, I see it as an advantage to simply reuse DBT's framework, which has (1) [YML-based tests for schemas](https://docs.getdbt.com/docs/testing#section-schema-tests) and (2) [SQL-based tests for data](https://docs.getdbt.com/docs/testing#section-custom-data-tests). We can of course supplement these with more.

I note that it also has no 'downtime' (like our current scripts) and good logs and command output. It generates nice documentation about tables, that is richer than our current documentation (visual relationship between tables, links to the SQL source…). It's also possible to set target/custom schemas, which is a feature we need.

None of this is revolutionary, but I'd rather reuse a tool if it meets our needs, rather than have another custom framework to maintain. (Hence why we use Scrapy, Django, Sphinx, SaltStack, Transifex, etc.). Kingfisher Views isn't a lot of code, but if DBT means we can delete half of it, then that seems like better long-term planning.

Our requirements might also change over time, and it looks like DBT can already satisfy some requirements and/or will grow to meet future needs – whereas Views's framework is 100% on us to improve.

**Comment by robredpath** [comment]
DBT looks really good; it looks like it's been designed for the purpose that we're proposing to put it to, and offers features that we'd find helpful. 

Before we decide, I'd like to know what the training would look like in order for someone who has a typical OCDS Helpdesk analyst skill set to get up to speed with DBT. I've not completed the sample project, but it'd be good to know if doing that is sufficient for someone to get stuck in, or whether they would then need to go and learn more. We can, of course, ensure that all our current analysts are trained in using DBT and add it to onboarding documentation, but I think it'd be useful to know what that's like before we commit, just in case it transpires to be awkward! 

If we do go ahead, I think we should be clear on documenting what the workflow looks like for someone to make a change, in practice - addressing questions like "how do I try things out?" as well as version control and deployment. We have a well-mapped-out understanding of what the process of making changes to kf-views is, so making the update should be quite straightforward, but I think it's an important thing for us to do as part of the transition.

**Comment by jpmckinney** [comment]
Sounds good! Thanks @robredpath.

**Comment by jpmckinney** [comment]
Analysis document: https://docs.google.com/document/d/1uJw6Z1VljmEmISgy6HYQpVEn-FRxoYJm9HHaWT8523M/edit#

Trello card also had useful discussion.
