### ISSUE TITLE
Move drop table tmp_release_summary cascade to an 009 file

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#102]
Otherwise, if a developer is working on 008, they'll need to run 002 then 008, since tmp_release_summary is created in 002, and 008 depends on it, but also drops it.

By moving it to an 009 file, a developer can just re-run 008 as often as they like.

**Comment by kindly** [comment]
agreed, I was going to suggest this too.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kf-views: Move drop table tmp_release_summary cascade to an 009 file](https://trello.com/c/xbj94cYw/214-kf-views-move-drop-table-tmpreleasesummary-cascade-to-an-009-file)

**Comment by Bjwebb** [comment]
Done in https://github.com/open-contracting/kingfisher-views/pull/117
