### ISSUE TITLE
parties_summary.identifier is null if identifier.scheme is not provided

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#105]
Sometimes publishers share draft data in which `parties.identifier.id` and `parties.identifier.legalName` are provided but `parties.identifier.scheme` is not.

For those cases, in views, `parties_summary.identifier` is null because concatenating a null value and a string results in a null value (https://github.com/open-contracting/kingfisher-views/blob/master/sql/002-tmp_release_and_parties.sql#L115).

We nearly got caught out when preparing feedback for Makueni County as one of the checks in the data feedback notebook was reporting that no identifiers were provided based on `parties_summary.identifier` being null.

@kindly given that `.scheme` isn't a required field, should `parties_summary.identifier` be populated, even when `.scheme` isn't provided or was this by design?

cc @mrshll1001 @odscrachel

**Comment by duncandewhurst** [comment]
In Pelican, coverage of `parties.identifier` is reported as 100% in the Makueni data, so it would be good to be consistent across the two tools:

![image](https://user-images.githubusercontent.com/19265814/77496106-16daed80-6eaf-11ea-858d-4bf6acce2d44.png)

**Comment by duncandewhurst** [comment]
Likely also affects `buyer_summary`, `procuringEntity_summary`, `tenderers_summary` and `award_suppliers_summary`

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kf-views bug: not providing an (optional) identifier scheme causes identifier to be blank](https://trello.com/c/2GS98Lno/212-kf-views-bug-not-providing-an-optional-identifier-scheme-causes-identifier-to-be-blank)

**Comment by Bjwebb** [comment]
In https://github.com/open-contracting/kingfisher-views/commit/10dd81f5641091a09fcd33ecc427880813f42d9a I replace our use of `||` in these cases with `concat_ws`, which will ignore any values that are null and use the rest. By default this returns the empty string `''` if both of the values are null. @duncandewhurst Is this okay, or should I add extra logic to make it null in this case?

**Comment by duncandewhurst** [comment]
Thanks @Bjwebb I think returning `null` would be more consistent with the behaviour of other fields in Kingfisher Views when the source field is missing from the OCDS data

**Comment by jpmckinney** [comment]
Closed by #150
