### ISSUE TITLE
Add support for releases published as part of a record (release_type = 'embedded_release')

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#110]
My understanding is that, for record collections, currently kingfisher-views only summarises the `compiledRelease` and doesn't do anything with the `releases` array.

This means that for publishers that only publish records, we can't do release-level analysis using kingfisher-views.

How much work would it be to also summarise the individual releases provided as part of a record?

We'd need some way of distinguishing these from the compiled release summaries, which I guess could be done by adding a new `release_type`.

For context, this came up when reviewing Paraguay's draft data, which was only shared as records.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support in Views for releases published as part of a record](https://trello.com/c/TTJjrdXT/211-add-support-in-views-for-releases-published-as-part-of-a-record)

**Comment by kindly** [comment]
I do not see that as a problem.  Only we do not want to do it for records with linked releases, so as long as we find a way of detecting them we can another `release_type` for this.  Take about a day to do.

**Comment by duncandewhurst** [comment]
Thanks @kindly 

In https://github.com/OpenDataServices/cove/issues/895 we decided the best was to differentiate between linked and embedded releases was to check for the `id` field.

**Comment by jpmckinney** [comment]
The specific comment is: https://github.com/OpenDataServices/cove/issues/895#issuecomment-529915656

OCDS Kit has a somewhat different test: https://ocdskit.readthedocs.io/en/latest/api/util.html#ocdskit.util.is_linked_release The main addition is that it tests the number of fields.

**Comment by Bjwebb** [comment]
@duncandewhurst This has been deployed to the server. Could you check this now works as expected?

**Comment by duncandewhurst** [comment]
Thanks @Bjwebb 

I created `view_data_collection_1261` to test this. It looks how I would expect apart from a couple of things:

* In the `release_summary_with_data` table, the `data` column for releases with type 'releases_within_record' contains the whole record. I would expect it to contain just the release which is summarised on that row.
* In the `field_counts` table all paths (e.g. `compiledRelease/...`, `versionedRelease/...`, `releases/...` etc.) are listed twice, once with `release_type` set to 'record' and once with it set to 'releases_within_records'. For the latter I would expect to see just the paths under `releases/`.
* We tend to refer to releases within records as embedded releases, so 'embedded_release' might be a better value to use in `release_type` than 'releases_within_records'.

Also, the documentation will need updating (the `release_type` column description in the database tables reference section and the 'how tables are related' section).

**Comment by Bjwebb** [comment]
Thanks @duncandewhurst. Those are all useful suggestions, and look easy to change.

When I update the data column of `release_summary_with_data`, I automatically get a change to `field_counts`:
![Screenshot from 2020-07-08 17-38-05](https://user-images.githubusercontent.com/634/86946121-d5124200-c141-11ea-925e-498e3d965b01.png)
This has just the paths under `releases/`, but without that prefix. Is this okay? I can add the prefix back in if that's useful, it just might be some amount of faff.

**Comment by duncandewhurst** [comment]
Without the prefix is better! Thanks

**Comment by Bjwebb** [comment]
@duncandewhurst The latest changes are now on the kingfisher server, if you want to review.

Just noticed that the docs still need updating, so I'll look into that.

**Comment by Bjwebb** [comment]
I've made some update to the docs: [PR](https://github.com/open-contracting/kingfisher-views/pull/125), [view on Read the Docs](https://kingfisher-views.readthedocs.io/en/110-embedded-release-docs/database.html)

**Comment by jpmckinney** [comment]
Is #43 related / duplicate?

**Comment by duncandewhurst** [comment]
As @yolile said, #43 relates to summarizing compiled releases published as part of a record, whereas this issue relates to summarises embedded releases

**Comment by duncandewhurst** [comment]
@Bjwebb the changes and docs look good, thanks!
