### ISSUE TITLE
Docs: Update the database tables reference section is wrong

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-views#112]
https://kingfisher-views.readthedocs.io/en/latest/develop.html#update-the-database-tables-reference

`docs-table-ref` needs to be passed a view name now.

Don't even try this one until #111 is merged

**Comment by jpmckinney** [comment]
Added the missing argument in the example command in bc51d42c1caa7ded211ca7b79464e66c26cfaaa2
