### ISSUE TITLE
Correct user permissions broken (and hence add view)

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-views#122]
https://github.com/open-contracting/kingfisher-views/blob/master/ocdskingfisherviews/correct_user_permissions.py#L7 
This tries to load the user list from a database table, but it looks like the table has now moved?

Now you get a error "relation not existing"

Because add view calls correct user permissions this crashes to. But important to note, the view/schema is still created - it's just that read only users won't be able to see it.

**Comment by jpmckinney** [comment]
Hmm, perhaps the migrations just need to be run?

**Comment by odscjames** [comment]
Ah sorry, should have been clearer. This error was seen on live server.

So if it is just a migration thing, then something is wrong with the deploy process. In any case, the live server is currently broken.

**Comment by jpmckinney** [comment]
I had to deploy manually in order to not restart PostgreSQL, but must have forgotten the migration. I ran the command now and it completed successfully.
