### ISSUE TITLE
Sample .ini no longer exists 

### ISSUE THREAD

**Issue by astenuz** [open-contracting/kingfisher-views#124]
The getting started guide prompts to download a sample configuration using the command

```sh
curl -o ~/.config/ocdskingfisher-views/config.ini https://kingfisher-views.readthedocs.io/latest/en/_static/config.ini
```

However, the file no longer exists and the command ends up downloading a 404 webpage

**Comment by jpmckinney** [comment]
Thanks for reporting. The URL had a typo: https://kingfisher-views.readthedocs.io/en/latest/_static/config.ini

Fixed in 42ecd835a443a6db2cdd3f33420bec761ecb8922
