### ISSUE TITLE
Follow consistent pattern for *_summary_no_data tables and *_summary views (and data column names). Merge release_summary_with_checks table into (renamed) release_summary view.

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#132]
There's a couple of things I find confusing in the current set-up:

1. For some tables (e.g. `tender_summary`) there is a separate `_with_data` table with an extra column which contains the  object being summarzed in jsonb format and in other tables (e.g. `awards_summary`) the jsonb column is already included.

2. In the `release_summary_with_data` table the column with the jsonb object is named `data` but in other tables the column is named after the object, e.g. `tender`, `award` etc.

I would find it easier to use if:

1. We remove `_with_data` tables (and `_with_checks`) and instead include the jsonb columns in the main tables.

    * [x] release_summary_with_data (view)
    * [x] tender_summary_with_data (view)
    * [x] release_summary_with_checks (view)

2. We rename any columns named `data` to the name of the object they contain, e.g. `release`.

    * [x] release_summary_with_data

This would likely break some analyst templates, but we could fix them on the next run through and it would make them easier to maintain going forward.

@mrshll1001 @pindec @odscrachel @yolile @romifz - what do you think? Are there any external users this would cause a problem for?

**Comment by mrshll1001** [comment]
> Are there any external users this would cause a problem for?

None that I can think of.

> We rename any columns named data to the name of the object they contain, e.g. release.

Yes please! This makes a lot more sense and I think this is how it's done in some tables already e.g. [parties_summary.party](https://kingfisher-views.readthedocs.io/en/latest/database.html#parties-summary)

**Comment by yolile** [comment]
I totally agree with your suggestions @duncandewhurst ! but
> Are there any external users this would cause a problem for?

Yes, there are at least two users in Paraguay who are using kingfisher-views and will need to change their implementation to align with this change, but I think I can talk to them and let them now.

**Comment by jpmckinney** [comment]
@yolile Are those users connecting to our database, or creating their own databases?

**Comment by yolile** [comment]
They are using their own, but they will need to update their queries/app to use these tables/columns (as they are updating their databases with the `refresh-views` command)

**Comment by jpmckinney** [comment]
@yolile Ah okay. I was just thinking that, as long as they don't upgrade, they can leave the queries as-is :)

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kingfisher-views: Merge additional columns in _with_data and _with_checks tables into main tables](https://trello.com/c/iSj7eGjc/236-kingfisher-views-merge-additional-columns-in-withdata-and-withchecks-tables-into-main-tables)

**Comment by pindec** [comment]
Agree this would be more intuitive to users (including us :)). 

The `_with_data` tables are generated from the summary tables (e.g. `tender_summary_with_data` just joins data onto `tender_summary`). I think the original use case for that was to enable more efficient querying where looking at the raw JSON was not required. But since that hasn't been done consistently then rationalisation makes sense.

So my only concern is whether a new release table with both `_data` JSONB and all the `_checks` JSONB would be unwieldy for large queries.

I don't know of any live Kingfisher Views users of `_with_data` via current colab notebooks. I used `release_summary_with_data` in a hackathon colab notebook but as yet it's not in use.

**Comment by jpmckinney** [comment]
I notice that for awards, contracts, and parties, the pattern is a **table** named `awards_summary_no_data` and then a **view** named `awards_summary`. So, we should just follow the same pattern for `tender` and `release`.

I also don't see any problem with merging `release_summary_with_checks` (the only `_with_checks` table) into the new `release_summary` (what is now named `release_summary_with_data`).

**Comment by jpmckinney** [comment]
Closed by #149 and notified in CRM-6535
