### ISSUE TITLE
field_counts table only has one entry

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#134]
I summarised collection 1395 which is an OCDS for PPPs record collection with 22 records containing both compiled and embedded releases. The views schema is `view_data_collection_1395`.

As expected, `release_summary` has 44 entries (22 with type `record` and 22 with type `embedded_release`).

However, `field_counts` only has one entry:

index | collection_id | release_type | path | object_property | array_count | distinct_releases
-- | -- | -- | -- | -- | -- | --
0 | 1395 | embedded_release | awards | 12 | 27 | 12

Edit: This is interfering with providing feedback to a publisher. I've added a new 'blocker' label we can use to tag such issues.

**Comment by jpmckinney** [comment]
Fixed in 71f6b7040b22c4deaa345b585e4bfff3fb81907f

The tests haven't historically tested the data in the tables. We should add such tests to avoid this type of bug.

**Comment by jpmckinney** [comment]
I ran field-counts and correct-user-permissions, so you should see all rows now.
