### ISSUE TITLE
json 2 sql server

### ISSUE THREAD

**Issue by vlasvlasvlas** [open-contracting/kingfisher-views#136]
Hi! i was looking for a tools that let me convert the json to standard .sql files, i'm trying to import a release package into sql server using this structure https://kingfisher-views.readthedocs.io/en/latest/database.html , and wondering if there is a tool that's already inside kingfisher that may help me in this job.

is there a tool available that may help me with this data import 2 sql server using kingfisher database structure?

i am aware of this .sql files: https://github.com/open-contracting/kingfisher-views/tree/master/sql

but they are prepared to get data from a json / jsonb postgresql data type,i was wondering if there are any openjson() input sql server files

thanks!
love the project!

**Comment by jpmckinney** [comment]
Hi @vlasvlasvlas, I see your other issue here: https://github.com/open-contracting/kingfisher-process/issues/314

Can you send an email to the OCDS Helpdesk at data@open-contracting.org ? They will be happy to better understand your needs, and suggest some options.

**Comment by jpmckinney** [comment]
Closing in favor of OCSD Helpdesk support.
