### ISSUE TITLE
Replace || with concat_ws; document when to use ||

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#151]
To fix #105 and #106, #150 uses `concat_ws` instead of `||`.

We still have a lot of occurrences of `||`.

Should these all be `concat_ws`? If not, when is it appropriate to use one or the other?

cc @Bjwebb

**Comment by Bjwebb** [comment]
Looks to me like every occurrence of `|| '-' ||` could be replaced by a `concat_ws` statement.  The reason not to do that is if any of our checks or scoring rely on them being null if one side is null.

**Comment by jpmckinney** [comment]
Thanks! I've changed the issue title.

**Comment by jpmckinney** [comment]
It turns out all current cases are concatenating schema and id, so I just added a new function to do that.
