### ISSUE TITLE
Does anyone use the refresh-views or field-counts commands?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#162]
Those two commands are documented here:

https://kingfisher-views.readthedocs.io/en/latest/cli/use.html#refresh-views

https://kingfisher-views.readthedocs.io/en/latest/cli/use.html#field-counts

I don't see much difference compared to just running delete-view then add-view.

@yolile @aguilerapy @duncandewhurst @mrshll1001 @pindec @odscrachel

**Comment by aguilerapy** [comment]
I think I never had the chance to use them.

**Comment by yolile** [comment]
I have used `refresh_views` for view_data_colombia, to include more recent data. However, yes, I could have used delete-view and add-view instead.

**Comment by jpmckinney** [comment]
I'll go ahead with this change.

While working to parallelize the creation of summary tables #163, it gets really complicated to allow dropping and re-creating tables in the correct order without errors about foreign key constraints, etc. – issues around `--tables-only` being used in one direction and not the other, etc.

If users need to retain access to the schema while it's being rebuilt, they can just create a new, separate schema, and then delete the old schema when the new one is ready. The only good use cases are for development, but there are alternatives to that, and in any case parallelization will make execution order non-deterministic, such that a programmatic solution to reversing a SQL file is probably too much effort.
