### ISSUE TITLE
Document unique_identifier_attempt

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#17]
e.g.

> Either the party's `id`, `{identifier.scheme}-{identifier.id}` or `name`, depending on which fields are available.

**Comment by jpmckinney** [comment]
It was noted in the end-of-sprint call on 2019-06-25 that we can add more documentation about the tables more generally (how to interpret calculated columns, how they are calculated, etc.).

cc @duncandewhurst @kindly who raised this.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve docs of kingfisher-views and kingfisher-process database](https://trello.com/c/3N0ylJE5/96-improve-docs-of-kingfisher-views-and-kingfisher-process-database)

**Comment by duncandewhurst** [comment]
@kindly - what was the intended scope of the uniqueness of these identifiers?

`party.id` need only be unique within the scope of a contracting process for the data to conform with OCDS, so if the intent was for the identifier to be unique across the dataset, then we shouldn't use this.

Identifiers which are unique across the whole dataset would be most useful (to avoid analysts having to add conditions to their queries based on whether a publisher has provided good organization identifiers or not), so even if this wasn't the intent, we should either change how these fields are constructed or add another field with a unique-across-the-dataset identifier.

**Comment by kindly** [comment]
Fields are now documented via #96.

I think the intent was for this was to have a way to joining to the parties array if the identifiers were bad.  Howerver, agreed I think we should have a unique across database field.
