### ISSUE TITLE
Critical service error - award/transaction values in KF views

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/kingfisher-views#170]
**Which service is affected?**

Kingfisher views

**What were you trying to do?**

Analyzing the data for data review I noticed that award values and implementation transaction values are not in the associated tables and values are showing as null despite the numbers being in the raw data. 

**What error did you receive?**

See the following queries to show [award values](https://redash.open-contracting.org/queries/251/source#352) and [implementation values](https://redash.open-contracting.org/queries/258/source) being null despite being in data. 

**Did you attempt a fix?**

No

**Comment by jpmckinney** [comment]
Fixed in bd3233075d458e27d9d7bdca1508330433d20307

Bug was introduced on November 2

Test added to avoid regression.

Deployed.

**Comment by jpmckinney** [comment]
Note: If we want to restore the second argument to the conversion functions, we need to remove `STRICT`.
