### ISSUE TITLE
Fix typo in *_items_summary.item_classifiaction

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#21]
`item_classifiaction` should be `item_classification` in all the `x_items_summary` views.

**Comment by robredpath** [comment]
@duncandewhurst FYI this has been fixed without adding a new field (as per your comment on Trello) so queries will need to be modified.

**Comment by jpmckinney** [comment]
Ah, I hadn't seen the Trello comment (not sure which card it is as not attached here). Anyhow, it should be easy to identify the queries to fix (and to fix them), as they will fail on newly created views/schemas.
