### ISSUE TITLE
Spreadsheet access to kf-views

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-views#22]
Kingfisher-views is really helpful for lots of analysis use, but of course it's in a database. What could we do to make spreadsheet versions available?

**Comment by jpmckinney** [comment]
Noting that 360Giving has a landing page about access to their datastore: https://www.threesixtygiving.org/data/360giving-datastore/ Also related to #1.

**Comment by jpmckinney** [comment]
Analysts can use Google Colaboratory and Kingfisher Colab to query views (using `get_dataframe_from_query`) and then export the results to a sheet (using `save_dataframe_to_sheet`).

For external access, I created a new issue: open-contracting/kingfisher#350 Once we've advertised the data's availability, we can explore external users' needs and go from there.
