### ISSUE TITLE
awards_suppliers_summary.supplier_additionalidentifiers bug

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#23]
I think there might be an issue with the following fields:

* award_suppliers_summary.supplier_additionalidentifiers_ids
* award_suppliers_summary.supplier_additionalidentifiers_count

Looking at collection 534 (australia federal) those fields are always `null` and `0` respectively:

```sql
select distinct
  supplier_additionalidentifiers_ids,
  supplier_additionalidentifiers_count
from
  views.award_suppliers_summary
where
  collection_id = 534
```

However there are additional identifiers for suppliers in that collection, e.g.

```sql
select
  roles,
  parties_additionalidentifiers_ids,
  parties_additionalidentifiers_count,
  party -> 'additionalIdentifiers'
from
  views.parties_summary
where
  collection_id = 534
and
  ocid = 'ocds-d2phr6-c1954baba13b3c2a31a63302a0f9cb66'
and
  release_id = 'ocds-d2phr6-c1954baba13b3c2a31a63302a0f9cb66-15b0cfde81ff3124a4419de2fc45756e'
```

results in:

roles | parties_additionalidentifiers_ids | parties_additionalidentifiers_count | additionalidentifiers
-- | -- | -- | --
[supplier] | [AU-ABN-47001407281] | 1 | [{'id': '47001407281', 'scheme': 'AU-ABN'}]

**Comment by jpmckinney** [comment]
It's the same bug as #45. I'll comment there and close here.
