### ISSUE TITLE
Document _index fields and how they should be used

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#25]
e.g. `contracts_summary.contract_index`,  `parties_summary.party_index` etc.

My understanding is that we should use these fields in joins, instead of the `id` fields in the arrays, in case there are issues with duplicate identifiers in the publisher's data.

As well as providing a description for these fields in the reference tables, I think this warrants some additional guidance for users.

cc @mrshll1001

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve docs of kingfisher-views and kingfisher-process database](https://trello.com/c/3N0ylJE5/96-improve-docs-of-kingfisher-views-and-kingfisher-process-database)

**Comment by jpmckinney** [comment]
I think this was closed by https://github.com/open-contracting/kingfisher-views/pull/96
