### ISSUE TITLE
Document a description for each field in each view

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#26]
Just adding an issue so we don't lose track of this task.

**Comment by jpmckinney** [comment]
We can add the Views issues to I&R, as analysts see fit.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve docs of kingfisher-views and kingfisher-process database](https://trello.com/c/3N0ylJE5/96-improve-docs-of-kingfisher-views-and-kingfisher-process-database)

**Comment by kindly** [comment]
closed via #96
