### ISSUE TITLE
Establish a process for creating read only logins for external users

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#28]
Rather than handing out the generic read only user login details to external users that want to connect to the kingfisher database, it would be preferable if we could create individual accounts for external users which we can then control/revoke access to.

This will be some extra admin work, but it is a very powerful tool for demonstrating how users can work with OCDS data.

This issue crosses kingfisher-process too, so I'll open another issue there and reference this one.

**Comment by jpmckinney** [comment]
I know many users have access through Redash (which already has per-user accounts), and through which it is possible to query views. Can you describe the level/need of use of direct PostgreSQL connections by external users?

**Comment by odscjames** [comment]
Creating more read only postgres users would all be handled in Salt deploy scripts actually. We'd need to make sure there was some salt stuff to remove users when they are no longer needed, too. I don't expect this would take long. I'll leave others to discuss user need and prioritise.

**Comment by duncandewhurst** [comment]
> I know many users have access through Redash (which already has per-user accounts), and through which it is possible to query views. Can you describe the level/need of use of direct PostgreSQL connections by external users?

This useful for when we want to share colab notebooks with example queries (and proximate documentation of the results of those queries) with data users.

That's the demand we've seen so far, but it would also be useful for any users that wanted to connect other analysis tools to the kingfisher views database.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it easier to create new read-only users for the hosted Kingfisher database](https://trello.com/c/BE9JOi2Z/133-make-it-easier-to-create-new-read-only-users-for-the-hosted-kingfisher-database)

**Comment by odscjames** [comment]
Noting that creating extra read-only users who have all the full access of the current read-only user is easy, but in #1 there is more demands about giving only limited access and both bits of work should be thought about together.

**Comment by robredpath** [comment]
@odscjames can we separate out the work of creating extra users that are the same as the current one, and reworking the permissions? The former feels much easier,  immediately do-able and immediately useful; whereas the latter needs some further definition.

**Comment by odscjames** [comment]
>   the work of creating extra users that are the same as the current one

So actually it turns out that this is in process already because of  https://github.com/open-contracting/kingfisher-views/pull/47 - that broke the current way we make read only users, so we had to do something to put back a new way. We'll look at this and make sure this is fully written up somewhere.

> reworking the permissions

This will be more work, so I would support doing it separately.

**Comment by odscjames** [comment]
This issue is about giving users access to whole database, this is now done.

https://github.com/open-contracting/kingfisher-views/issues/1 is about giving access to part of the database.

I will therefore close this issue
