### ISSUE TITLE
Add description fields to views tables

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#33]
Currently the views tables include title fields (e.g. `tender_title`, `award_title` etc.) but not description fields (e.g. `tender_description`, `award_description` etc.).

It would be useful to have the description fields available in the views tables, as searching across those is sometimes necessary to identify contracts related to a particular project.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kingfisher-views: Add new aggregates/fields](https://trello.com/c/1Ta2HPcR/105-kingfisher-views-add-new-aggregates-fields)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Finish up and merge work on Views that's been started and responds to analyst requests](https://trello.com/c/X3wOJIhz/262-finish-up-and-merge-work-on-views-thats-been-started-and-responds-to-analyst-requests)
