### ISSUE TITLE
Re-think code-level integration with Kingfisher Process

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#34]
## Issue

Views installs all of Process, just to read its configuration, just to get a database URI.

## Background

We chose to store Process' config in the `.config` directory instead of [in the environment](https://12factor.net/config) (e.g. by setting the environment variable in the `ocdskfp` user's shell configuration file) for a variety of reasons, including making it easier for users to run locally, without us having to provide instructions for a variety of shells and OSes. We have indeed seen interest by third-parties in running it locally.

My understanding is that users rarely if ever use Views' CLI, unless they are debugging or testing its deployment (or running the development commands locally). Otherwise, the CLI is always used in the context of a cron job.

For our deployment, my understanding is that we're only interested in calculating Views on the main Process database, and that there has been no demand for doing so on other databases (assuming that we even have any and that analysts aren't always all using the main database).

## Proposal

Instead of installing all of Process, and instead of separating config-reading into a new repo (e.g. `kingfisher-config`), I propose that Views simply read the database URI from an environment variable. In our deployment, we can set the database URI for the main Process database in the relevant users' shell configuration files and in the cron job (which I assume can be done with Salt).

This seems to be the simplest possible solution. If/when we have clear use cases for more complex solutions, we can pursue those.

**Comment by robredpath** [comment]
@jpmckinney Are you envisaging alternatives to kingfisher-process that share a database schema but aren't kingfisher-process? Or, someone connecting to a shared Process database but running their own Views? As I understand it, both Views and Process are almost always going to be installed together as it's Process that loads the data that Views then works on. So, while I agree that separation is desirable, in practice I don't immediately see when you'd want to run Views without Process at all.

**Comment by jpmckinney** [comment]
I'm thinking that it would be strange for every system (especially non-Python systems) to have to install Kingfisher Process, just to get its code for determining a database URI.

The Data Quality Tool, for example, is just given a database URI – it doesn't install Kingfisher Process to get that piece of information.

I figure that, similarly, Views could be a little more independent, and just be given a database URI, and not install Process just to run some code for getting that URI.

**Comment by kindly** [comment]
The other reason for doing this was for consistency with process cli code structure i.e having the commands work in the same way with the same config objects as in process.

Having to have an environment variable for the command line tool is not optimal when using or testing  locally.  Process config does support environment variables also.

My preferred approach is just having a cutdown copy of:

https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/config.py

within views itself.  It will not end up being much code and will not matter if these classes diverge.  

I mainly like this approach as it would be the least about of work, be backwards compatible and mean we would not need to change the deploy scripts.

**Comment by jpmckinney** [comment]
> Having to have an environment variable for the command line tool is not optimal when using or testing locally. Process config does support environment variables also.

Good point. We can instead follow a pattern from Django projects, used to hide private settings, where an e.g. `local_settings.py` file is imported (and if it's not present, the exception is ignored). A developer can locally store the database URI in that settings file, which would be ignored by git.

I don't especially like the idea of other apps reading Process' configuration files, environment variables, etc. My proposal offers a very simple contract to other apps, which is that Views can rely on Process' database schema being stable.

The alternative proposal offers a more demanding contract, which is that other apps can rely on Process' environment variables and configuration files having stable structures and semantics (in addition to the database schema being stable). I don't see why Process' public API/assets should expand to these things. I think Process should have the freedom to change these at any time.

This might be a *little* more work, but I think it is a better design for the future.

**Comment by kindly** [comment]
@jpmckinney 
How about having a cutdown version of:
https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/config.py

but also changing the config location to `~/.config/ocdskingfisher-views/config.ini`
and the environment variable to ''KINGFISHER_VEIWS_DB_URI"

This way we keep the same pattern as process without sharing the variables.  The deploy will just mean copying the same file essentially to a new location.

**Comment by jpmckinney** [comment]
That sounds fine, too!

**Comment by odscjames** [comment]
Think this counts as done!
