### ISSUE TITLE
reinstate requirements.txt

### ISSUE THREAD

**Issue by kindly** [open-contracting/kingfisher-views#35]
We need requirments.txt to make sure that the server deploys are consistent.

Views is not currently a library and nor is it used as one, so just using setup.py will not work as well.

@jpmckinney I am not sure they were removed?

Can I go ahead and reinstate it?

**Comment by jpmckinney** [comment]
Yes, we can reinstate. I got confused by the presence of `setup.py` in both Process and Views, which Views used to install Process and to install itself in .travis.yml.

As part of this, we should remove `setup.py`, which seems to serve no function anyhow. We can also remove `MANIFEST.in` and remove `/*.egg-info` from .gitignore, which were only added to be consistent with a `setup.py` installation.

**Comment by jpmckinney** [comment]
I have a PR open #37
