### ISSUE TITLE
award_suppliers_summary: sometimes the supplier_identifier column is empty

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#39]
For example, in hosted kingfisher, the following query returns no results, even though the data contains supplier identifiers:

```sql
select distinct supplier_identifier from views.award_suppliers_summary where collection_id = 621
```

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [award_suppliers_summary: sometimes the supplier_identifier column is empty](https://trello.com/c/sw1TVcsP/177-awardsupplierssummary-sometimes-the-supplieridentifier-column-is-empty)

**Comment by jpmckinney** [comment]
Same problem as #45
