### ISSUE TITLE
Fix installation of Process in Travis config

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#41]
Right now it pip installs Process, but Process will lose its setup.py file https://github.com/open-contracting/kingfisher-process/issues/200. The alternative is to git clone Process's repo and pip install its requirements, but this presently causes flake8 issues because Process (uniquely) uses a different flake8 line length than all other OCP projects.

The resolutions are either:

1. Install Process where flake8 won't see its files (expedient)
1. Run flake8 before installing Process (not preferred, as it mixes the roles of `before_script` and `script`)
1. Change Process to use the same line length as all other projects (preferred)

**Comment by odscjames** [comment]
The third option is probably best.

Once we've done that, https://github.com/open-contracting/kingfisher-views/commit/e83ec35a29d67a1550af9f52638e23767fa278ae should fix this.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)

**Comment by rhiaro** [comment]
Just to confirm, line lengths fixed in kingfisher-process https://github.com/open-contracting/kingfisher-process/commit/85f0316b3adcec62b7d1f1960765af57aaa7165a

**Comment by odscjames** [comment]
Now merged
