### ISSUE TITLE
Add `buyer_name` column to buyer_summary

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#44]
Publishers often don't have organization identifiers for buyers, so a common need is to summarise data by the buyer name.

Please can we add `buyer_name` as a column in the `buyer_summary` table?

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Finish up and merge work on Views that's been started and responds to analyst requests](https://trello.com/c/X3wOJIhz/262-finish-up-and-merge-work-on-views-thats-been-started-and-responds-to-analyst-requests)
