### ISSUE TITLE
Clean up unused code from rebuilding all views 

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#52]
@robredpath mentioned there was some cleanup to do on the review call.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move away from running Views overnight](https://trello.com/c/dJo6dMkG/161-move-away-from-running-views-overnight)

**Comment by robredpath** [comment]
Pretty sure we can close this now as the relevant Trello card is Ready for Done? but checking with @odscjames first.

**Comment by odscjames** [comment]
Yes.
