### ISSUE TITLE
sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-views#61]
When running script: 002-tmp_release_and_parties

**Comment by odscjames** [comment]
I think the problem is in the "    r.id * 10 AS id," bits of that script.
```

ocdskingfisherprocess=> select max(id) from release_with_collection; 
    max    
-----------
 216692634
(1 row)


```

2166926340 (that * 10) is bigger than:
2147483647, the limit of an integer column in the database.

Because of how CREATE TABLE ... AS SELECT is used, the id column in the new table is created as an integer type. Hence the out of range.

It might be that "*10" is used just to prevent ID collisions, and we can instead use "*3".

I would like to chat to @kindly about this.

**Comment by odscjames** [comment]
Deployed

**Comment by kindly** [comment]
This is not fixed as the previous pull request was wrong because the integer needs to be converted before being times by 10.

**Comment by odscjames** [comment]
Deployed by a manual git pull
