### ISSUE TITLE
Automate naming for views

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-views#65]
From Trello card from @pindec :

Camila suggested implementing automatic naming for views by default:
views_collectionid

This will be useful when running analysis across multiple collections without requiring analysts to either remember at creation time to use a consistent naming scheme, or having to run a query to find out what the views are all called.

However, we should allow analysts can override this if they want (to rename a view on a large number of collection ids).

Default for multiple collection ids (python ocdskingfisher-views-cli add-view 1,3 "Created by Fred.") should be views_collectionid1_collectionid3

See CRM 5444

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate naming for views](https://trello.com/c/oyfNonw9/175-automate-naming-for-views)

**Comment by kindly** [comment]
Finished and deployed #72
