### ISSUE TITLE
Consider adding comments/hints to identify the source of the query

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#66]
Follow-up to open-contracting/kingfisher-process#260

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add comments to Views queries](https://trello.com/c/epKLuTXX/209-add-comments-to-views-queries)

**Comment by robredpath** [comment]
@jpmckinney did you envisage these being entirely static (a bit like a UA string) or having some sort of dynamic info in (eg logged in user)?

**Comment by jpmckinney** [comment]
For Kingfisher Colab, this comment is a link to the Colaboratory notebook: https://github.com/open-contracting/kingfisher-colab/commit/04d7d22bf46142462be8d7a9a626137ec7018535#diff-2df8be8e47cdffb42750a9c23b19aadeR251

For Views, it should at minimum be `/*kingfisher-views*/`. We can alternately have it include the file being run (`/*kingfisher-views: 004-planning.sql*/`) or even the username as you suggest.

However, we might want to wait on #101 and https://trello.com/c/9T5UPfcL/204-review-options-for-frameworks-for-views before moving this forward.

**Comment by kindly** [comment]
Done a quick pull request for this #115 

I do not think we need to add user information as pg_stat_activity gives you the postgres user.
