### ISSUE TITLE
Consider alternative to bespoke CLI framework

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#70]
Consider using https://click.palletsprojects.com/en/7.x/

It has some nice testing functionality as well: https://click.palletsprojects.com/en/7.x/testing/

We presently only have tests for one command (refresh-views).

**Comment by robredpath** [comment]
@jpmckinney - we certainly like Click, and testing! IIRC we copied the pattern used in ocdskit so that there was some consistency across OCP tooling. Are you planning on migrating ocdskit to Click as well?

**Comment by jpmckinney** [comment]
Hmm, the code in https://github.com/open-contracting/kingfisher-views/tree/master/ocdskingfisherviews/cli doesn't look much like https://github.com/open-contracting/ocdskit/blob/master/ocdskit/cli/__main__.py so that desired consistency isn't achieved.

OCDS Kit inherits its pattern from [Pupa](https://github.com/opencivicdata/pupa/tree/master/pupa/cli), an unrelated project I contributed to. Since OCDS Kit already has a lot of tests, and a lot of customization of its CLI behavior, it'd be a fair amount of work to change the pattern, though the benefit might be simpler code (what Click offers) and greater consistency with other Click projects.

For Views, it'd be both simpler code and nice test functionality, so that we can get coverage up from 75%. Since most commands are fairly short, and since there is very little customization of the CLI behavior (cli/__init__.py and util.py are very short and mainly do what Click offers), I figure it'd be a much more straightforward project to convert Views to Click than OCDS Kit.
