### ISSUE TITLE
logzero: Do we need it?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#79]
We aren't using it to do anything more than what the default Python logging module offers.

**Comment by odscjames** [comment]
This was more @kindly than me, but I think it was just done for an easier setup and there would be nothing blocking a change if you want that?

**Comment by jpmckinney** [comment]
I prefer to remove the dependency and use the same logger as all other projects – especially since we aren't using its additional functionality / sugar.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Store outputs of add-view, refresh-views and field-counts](https://trello.com/c/T7uXC7kD/208-store-outputs-of-add-view-refresh-views-and-field-counts)

**Comment by jpmckinney** [comment]
Removed in #116
