### ISSUE TITLE
refresh-views: Do we need --sql-timing?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#80]
~~All it does is prepend a tab followed by "iming" to the SQL output (I assume this is a bug).~~

I don't know what that's useful for.

**Comment by jpmckinney** [comment]
I'm also not clear on why we need `--sql`, since it's just as easy to document that users can run `cat sql/name-of-file.sql` or (even better) open those files in their preferred text editor to get syntax highlighting, etc.

**Comment by kindly** [comment]
This is useful as it give timings per query not per file.   I am not sure if others need `--sql` but it also sets the `search path` correctly and was useful for debugging while developing.

**Comment by jpmckinney** [comment]
Is the timing code correct? My reading of the code (since its first commit) is as in the issue description.

**Comment by jpmckinney** [comment]
Aha, since it’s a regency string, the backslash is literal. Makes sense now.

**Comment by jpmckinney** [comment]
From my reading of the code, the search path is only set in the case where `--sql` is not set: https://github.com/open-contracting/kingfisher-views/blob/ffacce8ee379e786d5ef00014ab2f07c2e24cb89/ocdskingfisherviews/refresh_views.py#L56
