### ISSUE TITLE
refresh-views: SQL files depend on each other

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#83]
I'm not sure what the use case is for `--start` and `--end`. If it's only for testing purposes, then I think it's better to just test by running `psql -f sql/the-file.sql`.

Right now, there are many undocumented dependencies between the files, which users will be unaware of, and which will cause the command to fail (perhaps silently?):

* 1 is required by 2, 3, 4, 5, 6, 7, 8 (functions)
* 2 is required by 3, 4, 5, 6, 7, 8 (`parties_summary`, `tmp_release_summary`, `tmp_release_summary_with_release_data`)
* 4 is required by 8 (`planning_*_summary`)
* 5 is required by 8 (`tender_*_summary`)
* 6 is required by 7, 8 (`awards*summary`)
* 7 is required by 8 (`contracts*summary`)

The resolution is either to remove `--start` and `--end` (if there is a real use case besides testing), or to document the dependencies.

**Comment by jpmckinney** [comment]
For now, I'm removing this from the docs, and pasting the content I had copy-edited here:

```rst
Create specific tables
----------------------

Each SQL file in the `sql directory <https://github.com/open-contracting/kingfisher-views/tree/master/sql>`__ begins with a number (``001``, ``002``, etc.). You can run one or more of the files by setting the ``--start`` and/or ``--end`` arguments to integer values; the command will run the files matching the ``--start`` number up to the ``--end`` number (inclusive). If ``--start`` isn't set, the command will start from the first file (``001``); if ``--end`` isn't set, the command will end on the last file. For example:

.. code-block:: bash

   python ocdskingfisher-views-cli refresh-views NAME --start 4 --end 5

will run the files ``004-planning.sql`` and ``005-tender.sql``.
```

**Comment by kindly** [comment]
Happy to remove.  Was useful in early development.

The documentation should say that you need to run the previous stages before you can run the latter ones.  i.e you can only run 4-5 if you have already run 1-2-3.   The point of it really is that if you are working on 7 then you can run 1 to 7 then keep on just running 7 as you are iterating on it.
