### ISSUE TITLE
Replace any slow DISTINCT queries

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#88]
For example, using subqueries instead. DISTINCT queries tend to be very slow.

**Comment by kindly** [comment]
We are using `distinct on` not `distinct` and I have found `distinct on` to be surprisingly fast.

The reason for using it is to guard against `parties` that could having the same `id` fields and when joining to them, causing duplicate rows. 

For this case the other workarounds to stop duplicates eg using row_number and subqueries are in my experience are slower but may not be in all cases.  Here is the output of somebodies test that shows this https://rextester.com/ELL6912

**Comment by jpmckinney** [comment]
If we don’t have any that are slow, we can close :)
