### ISSUE TITLE
Consider storing output of add-view, refresh-views and field-counts

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#93]
I'm thinking we could store a copy of these commands' standard output to a file (e.g. `~/kingfisher-views-logs/COMMAND-SCHEMA_NAME.log`), so that we can manually read them for their timing information, and find slow steps/queries.

There are certainly more complicated alternatives (e.g. having a structured database of timing information and an analysis dashboard), but this seems like a fairly easy change that is good enough (just change the logger's configuration to write a file as well as print to standard output).

This would help identify slow steps like in #92.

We also shouldn't worry about the fact that, if a user re-runs a command for the same schema, then the log file is overwritten, because the timing information will be similar in both runs and we're just aiming to have a sample, not have a comprehensive logging system.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Store outputs of add-view, refresh-views and field-counts](https://trello.com/c/T7uXC7kD/208-store-outputs-of-add-view-refresh-views-and-field-counts)

**Comment by odscjames** [comment]
Views already uses logzero - it should be pretty easy to set that up so output is logged to a file as well as the screen. This should be a small job to do.

**Comment by jpmckinney** [comment]
See #79 for question about why we can't just use the plain Python logging module.

**Comment by odscjames** [comment]
Have deployed and done pull request for docs.

Logging currently goes into exactly same place as other kingfisher logs; in the absence of any user stories that that system has issues, it seemed easiest to use existing system.

**Comment by odscjames** [comment]
Now goes to /var/log/kingfisher-views.log

**Comment by jpmckinney** [comment]
Closed by #140.
