### ISSUE TITLE
kf-views throws 'relation "read_only_user" does not exist' when running in vagrant 

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-views#97]
(to refine - identified during docs sprint)

**Comment by robredpath** [comment]
Not sure whether to fix here as a prerequisites check, for example, or some setup stuff. Or in the Vagrant stuff https://github.com/open-contracting/kingfisher/issues/338

**Comment by jpmckinney** [comment]
I think Vagrant is missing the `upgrade-database` step, so leaving that other issue open.
